spring:
  datasource:
    url: jdbc:mysql://${BD_URL}:3306/${MYSQL_DATABASE}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


spring:
  datasource:
    username: ${MYSQL_USER}
spring:
  datasource:
    password: ${MYSQL_PASSWORD}

local:
  language: fr
local:
  country: FR
local:
  bundel: messages

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-lb/eureka
  zipkin:
    base-url: http://zipkin-svc/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
